"""Add health columns to CaughtPokemon

Revision ID: ef2d33d4d782
Revises: 29d2239d5ddc
Create Date: 2026-05-30 11:00:26.551253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef2d33d4d782'
down_revision = '29d2239d5ddc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('caught_pokemon', sa.Column('max_hp', sa.Integer(), nullable=True))
    op.add_column('caught_pokemon', sa.Column('current_hp', sa.Integer(), nullable=True))
    op.add_column('caught_pokemon', sa.Column('is_fainted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('caught_pokemon', 'is_fainted')
    op.drop_column('caught_pokemon', 'current_hp')
    op.drop_column('caught_pokemon', 'max_hp')
    # ### end Alembic commands ###